"""Quiz generation schemas."""

from typing import Literal

from pydantic import BaseModel, Field, field_validator


class GenerateQuestionRequest(BaseModel):
    """Request payload for batch MCQ generation."""

    topic: str = Field(min_length=1, max_length=120)
    difficulty: Literal["easy", "medium", "hard"] = "medium"
    question_count: int = Field(default=2, ge=2, le=2)


class QuizQuestionItem(BaseModel):
    """Single MCQ item generated by the LLM."""

    question: str
    options: list[str]
    correct_option_index: int
    explanation: str

    @field_validator("options")
    @classmethod
    def validate_options(cls, value: list[str]) -> list[str]:
        if len(value) != 4:
            raise ValueError("Exactly 4 options are required")
        if not all(isinstance(item, str) and item.strip() for item in value):
            raise ValueError("All options must be non-empty strings")
        return value

    @field_validator("correct_option_index")
    @classmethod
    def validate_correct_index(cls, value: int) -> int:
        if value < 0 or value > 3:
            raise ValueError("correct_option_index must be between 0 and 3")
        return value


class GenerateQuestionResponse(BaseModel):
    """Response schema for quiz batch generation."""

    topic: str
    difficulty: Literal["easy", "medium", "hard"]
    batch_size: int
    questions: list[QuizQuestionItem]

    @field_validator("questions")
    @classmethod
    def validate_questions_length(
        cls, value: list[QuizQuestionItem]
    ) -> list[QuizQuestionItem]:
        if len(value) != 2:
            raise ValueError("Exactly 2 questions are required per response")
        return value
